name: workflow-dispatch

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            --request POST \
            --url https://api.github.com/repos/benhpoh/workflow-dispatch-demo/actions/workflows/workflow-dispatch.yaml/dispatches \
            --header "authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"main"}'